CumulativeProject1/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CumulativeProject1.Areas.HelpPage.ModelDescriptions;
using CumulativeProject1.Areas.HelpPage.Models;

namespace CumulativeProject1.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

CumulativeProject1/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using MySql.Data.MySqlClient;
using CumulativeProject1.Models;
using System.Web.Mvc;

namespace CumulativeProject1.Controllers
{

    public class StudentController : Controller {

        /// <summary>
        /// GET: Student Index View
        /// </summary>
        /// <returns>
        /// The student index view
        /// </returns>

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// GET: Student/List View
        /// </summary>
        /// <param name="StudentSearchKey">
        /// a string that will search against student db by first name, last name, student number or enrollment date.
        /// </param>
        /// <returns>
        /// A list of students matching the StudentSearchKey
        /// </returns>

        public ActionResult List(string StudentSearchKey)
        {
            StudentDataController controller = new StudentDataController();
            IEnumerable<Student> Students = controller.ListStudents(StudentSearchKey);
            return View(Students);
        }

        /// <summary>
        /// GET: Student/Show/{id}
        /// </summary>
        /// <param name="id">id = studentid in my school data database</param>
        /// <returns>
        /// A view of the student object
        /// </returns>

        public ActionResult Show(int id)
        {
           StudentDataController controller = new StudentDataController();
            Student NewStudent = controller.FindStudent(id);

            return View(NewStudent);
        }
    }

}

CumulativeProject1/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using MySql.Data.MySqlClient;
using CumulativeProject1.Models;
using System.Web.Mvc;
using System.Diagnostics;

namespace CumulativeProject1.Controllers
{

    public class TeacherController : Controller {

        /// <summary>
        /// GET: Teacher Index View
        /// </summary>
        /// <returns>
        /// The Teacher Index view
        /// </returns>

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// GET: New Teacher View
        /// </summary>
        /// <returns>
        /// The New Teacher View
        /// </returns>

        public ActionResult New()
        {
            return View();
        }

        /// <summary>
        /// GET: Teacher/List View
        /// </summary>
        /// <param name="TeacherSearchKey">
        /// a string that will search against teacher db by first name, last name, hire date and salary.
        /// </param>
        /// <returns>
        /// A list of Teachers matching the TeacherSearchKey
        /// </returns>
        public ActionResult List(string TeacherSearchKey)
        {
            TeacherDataController controller = new TeacherDataController();
            IEnumerable<Teacher> Teachers = controller.ListTeachers(TeacherSearchKey);
            return View(Teachers);
        }

        /// <summary>
        /// GET: Teacher/Show/{id}
        /// </summary>
        /// <param name="id">id = teacherid in my school data database</param>
        /// <returns>
        /// A view of the teacher object
        /// </returns>
        public ActionResult Show(int id)
        {
           TeacherDataController controller = new TeacherDataController();
            Teacher NewTeacher = controller.FindTeacher(id);

            return View(NewTeacher);
        }

        /// <summary>
        /// POST: Teacher/Create
        /// </summary>
        public ActionResult Create(Teacher NewTeacher)
        {
            // C# Input Validation (Initiative)
            if (string.IsNullOrWhiteSpace(NewTeacher.TeacherFName) ||
                string.IsNullOrWhiteSpace(NewTeacher.TeacherLName) ||
                string.IsNullOrWhiteSpace(NewTeacher.EmployeeNumber) ||
                NewTeacher.HireDate == default(DateTime) ||
                NewTeacher.Salary <= 0) //salary input has to be higher than 0
            {
                Debug.WriteLine("Invalid input data. Please correct and try again."); //Logs the Error
                ViewBag.ErrorMessage = "Invalid input data. Please correct and try again.";
                return View("New");
            }

            NewTeacher.TeacherFName = NewTeacher.TeacherFName;
            NewTeacher.TeacherLName = NewTeacher.TeacherLName;
            NewTeacher.EmployeeNumber = NewTeacher.EmployeeNumber;
            NewTeacher.HireDate = DateTime.Now;
            NewTeacher.Salary = NewTeacher.Salary;

            TeacherDataController controller = new TeacherDataController();
            controller.AddTeacher(NewTeacher);

            return RedirectToAction("List");
        }

        //GET : /Teacher/DeleteConfirm/{id}
        public ActionResult DeleteConfirm(int id)
        {
            TeacherDataController controller = new TeacherDataController();
            Teacher NewTeacher = controller.FindTeacher(id);


            return View(NewTeacher);
        }

        //GET : /Teacher/Edit/{id}
        public ActionResult Edit(int id)
        {
            TeacherDataController controller = new TeacherDataController();
            Teacher SelectedTeacher = controller.FindTeacher(id);

            return View(SelectedTeacher);
        }

        //POST : /Teacher/Update/{id}
        [System.Web.Http.HttpPost]
        public ActionResult Update(int id, Teacher UpdatedTeacher)
        {
            TeacherDataController controller = new TeacherDataController();
            UpdatedTeacher.TeacherId = id;
            controller.UpdateTeacher(UpdatedTeacher);
            return RedirectToAction("Show/" + id);
        }

        //POST : /Teacher/Delete/{id}
        [System.Web.Http.HttpPost]
        public ActionResult Delete(int id)
        {
            TeacherDataController controller = new TeacherDataController();
            controller.DeleteTeacher(id);
            return RedirectToAction("List");
        }


    }

}

CumulativeProject1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/customStyles.css")">
    <title>Cumulative Project 3: mySchoolDb Application | Kyle Scott | N00352594 | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="@Url.Content("~/Content/validation.js")"></script>
   
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar">
        <div class="container">
            @Html.ActionLink("Cumulative Project 1: mySchoolDb Application | Kyle Scott | N00352594", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Teachers", "Index", "Teacher", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Students", "Index", "Student", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cumulative Project 3: mySchoolDb Application | Kyle Scott | N00352594</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>